djin_version: '0.10.0'

_default_run_options: &default_run_options
  options: "--rm --entrypoint=''"

tasks:
  "{{namespace}}integration":
    docker-compose:
      service: app
      run:
        commands: "cd /usr/src/djin && cucumber {{args}}"
        <<: *default_run_options
