version: "3.9"

services:
  app:
    build:
      context: .
      target: dev
    entrypoint: 'sh docker-entrypoint.sh'
    command: 'djin'
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/djin
    depends_on:
      - gitserver

  gitserver:
    image: catks/gitserver-http:0.1.0
    volumes:
      - ./docker/git_server/repos/:/var/lib/initial/
